const db = [
    {
        title: '小狸源码网',
        link: 'https://www.agmsy.com/',
        description: '游戏源码',
        tags: ['游戏源码', '游戏'],
        guoNei: true,
        account: '',
    },
    {
        title: 'java下载',
        link: 'https://www.agmsy.com/',
        description: 'java开发',
        tags: ['java', '编程'],
        guoNei: true,
        account: '',
    },
    {
        title: '个人博客',
        link: 'https://gteam_seven.gitee.io/my-blog/',
        description: '',
        tags: ['博客'],
        guoNei: true,
        account: '',
    },
    {
        title: 'steam游戏账号',
        link: 'https://kkdda.cn/',
        description: '',
        tags: ['游戏','steam'],
        guoNei: true,
        account: 'QQ1399435579登录',
    },
    {
        title: 'maven仓库查询',
        link: 'https://mvnrepository.com/',
        description: '',
        tags: ['maven','编码'],
        guoNei: true,
        account: '',
    },
    {
        title: '游戏开发网',
        link: 'https://www.yxkfw.com/',
        description: '',
        tags: ['游戏源码','游戏'],
        guoNei: true,
        account: '',
    },
    {
        title: '日月鸟',
        link: 'http://liuge.riyueniao.xyz/',
        description: '',
        tags: ['会员账号租聘'],
        guoNei: true,
        account: '',
    },
    {
        title: '仙侠小说专有名词随机生成器',
        link: 'https://hetu.dev/random-names/',
        description: '',
        tags: ['随机名称生成器','随机','游戏'],
        guoNei: true,
        account: '',
    },
    {
        title: '个人生活博客',
        link: 'https://gteam_seven.gitee.io/love/',
        description: '',
        tags: ['博客','生活'],
        guoNei: true,
        account: '',
    },
    {
        title: 'Cheat-GPT',
        link: 'https://ai.1688fa.com/#/chat/1002',
        description: '',
        tags: ['GPT','AI'],
        guoNei: true,
        account: '',
    },
    {
        title: '【像素角色生成工】Universal-LPC-Spritesheet-Character-Generator',
        link: 'https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator',
        description: '像素角色生成工',
        tags: ['像素角色','像素','游戏素材'],
        guoNei: true,
        account: '',
    },
    {
        title: '【像素角色生成工】Lpc-character-generator',
        link: 'https://pflat.itch.io/lpc-character-generator',
        description: '像素角色生成工',
        tags: ['像素角色','像素','游戏素材'],
        guoNei: true,
        account: '',
    },
    {
        title: 'Vega Ai',
        link: 'https://vegaai.net/r',
        description: 'AI绘画',
        tags: ['AI绘画'],
        guoNei: true,
        account: '',
    },
    {
        title: 'H游戏PC端',
        link: 'https://gteam_seven.gitee.io/game-collection',
        description: 'H游戏 ⑱禁✘',
        tags: ['H游戏','游戏'],
        guoNei: true,
        account: '',
    },
    {
        title: 'imagecolorizer【图像处理】',
        link: 'https://imagecolorizer.com/zh-tw',
        description: '1.免費自動為黑白照片上色\n2.透過放大臉部和細節，修復老照片。\n3.修復模糊和低質量的老照片，使其更清晰',
        tags: ['AI','图片处理'],
        guoNei: true,
        account: '',
    },
    {
        title: '易制地图',
        link: 'https://www.makeamap.cn/',
        description: '地图制作器',
        tags: ['游戏开发','地图制作器'],
        guoNei: true,
        account: '',
    },
]
for (let i = 0; i < db.length; i++) {
    db[i].key = i;
}
export default db